export const Colors = {
    text: '#12372A',
    border: '#436850',
    startButton: '#12372A',
    initialStartButton: '#FBFADA',
    resetButton: '#D04848',
    cancelButton: '#944E63',
    saveButton: '#436850',
    buttonTitle: 'white',
    disabledButton: '#E3E1D9',
    androidRipple: 'lightgrey',
    shadow: '#333',
    errorMessage: '#12372A',
    header: '#E1F0DA',
    headerBackground: '#436850',
    headerButton: 'white',
    addButton: '#E1F0DA',
    activeTab: '#E8C872',
    inactiveTab: '#FBFADA',
    screen: '#ADBC9F',
    dropdownBackground: '#D4E7C5',
    addText: '#294B29',
    itemBackground: '#436850',
    itemTexBackground: '#FDF0D1',
    itemName: 'white',
    checkBox: '#436850',
    checkBoxLabel: '#12372A',
    deleteButton: '#FFF8E3',
};

export const fontSize = {
    normalText: 16,
    inputText: 18,
    errorText: 16,
    buttonText: 17,
    activityText: 16,
    labelText: 16,
    checkBox: 14,
};

export const Padding = {
    itemPadding: 20,
    activityPadding: 5,
    containerPadding: 10,
    inputPadding: 8,
    textInputPadding: 10,
    checkBoxPadding: 5,
    buttonDefaultPadding: 1,
    buttonPadding: 8,
}

